In [1]:
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams,Distance,PayloadSchemaType,PointStruct,SparseVectorParams,Document,Prefetch,FusionQuery
from qdrant_client import models
import pandas as pd
from openai import OpenAI
import os
from dotenv import load_dotenv
import cohere

In [2]:
import openai
load_dotenv()

True

In [3]:
client=OpenAI()

In [4]:
QDRANT_URL = os.getenv("QDRANT_URL")

In [4]:
QDRANT_URL

'http://localhost:6335'

In [9]:
qdrant_client=QdrantClient(url=QDRANT_URL)

In [6]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    vectors_config={
        "text-embedding-model-3-small":VectorParams(size=1536,distance=Distance.COSINE)
    }
    ,
    sparse_vectors_config={
        "bm25":SparseVectorParams(modifier=models.Modifier.IDF)
    }
)

True

In [7]:
def get_embedding(text,model="text-embedding-3-small"):
    response=openai.embeddings.create(
        input=[text],
        model=model
    )
    return response.data[0].embedding

In [8]:
def get_embedding_batch(text_list,model="text-embedding-3-small",batch_size=100):
    if len(text_list)<=batch_size:
        response=openai.embeddings.create(input=text_list,model=model)
        return [embedding.embedding for embedding in response.data]

    all_embeddings=[]
    counter=1
    for i in range(0,len(text_list),batch_size):
        batch=text_list[i:i+batch_size]
        response=openai.embeddings.create(input=batch,model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        counter+=1
    
    return all_embeddings

In [9]:
df_items=pd.read_json("C:/Users/Anurag/OneDrive/Desktop/coading/Ai-engineering/Data/meta_Electronics_2022_23_with_categeory_rating_100_sample_2000.jsonl",lines=True)

In [10]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Electronics,Gvoears Replacement Ear Pads Cushions for Skul...,4.6,129,[【Perfect Compatibility】These ear pads are mad...,[],14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'the installation of earpads for sk...,G GVOEARS,"[Electronics, Headphones, Earbuds & Accessorie...",{'Product Dimensions': '3.94 x 3.15 x 0.98 inc...,B0BTBHYWY4,NaN,NaN,NaN
1,All Electronics,"Ethernet Splitter,NOBVEQ 1 Male to 2 Female Ne...",4.5,4654,[NOBVEQ RJ45 Ethernet Splitter: It converts th...,[],10.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],NOBVEQ,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '7.68 x 4.09 x 1.06 inc...,B0BWXS9QVY,NaN,NaN,NaN
2,Cell Phones & Accessories,Case for iPad 9th Generation 10.2 Inch 2021 iP...,4.5,110,[【Compatibility】 - Designed for 10.2-Inch iPad...,[],33.90,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Case for iPad 9th/8th/7th generati...,H HOLIMET,"[Electronics, Computers & Accessories, Tablet ...",{'Package Dimensions': '10.16 x 7.87 x 0.75 in...,B0BYCT8F2V,NaN,NaN,NaN
3,Camera & Photo,"Aipmoz Hidden Camera with 32G SD Card, Spy Cam...",4.8,107,[【Bluetooth Speaker Hidden Camera】This hidden ...,[],89.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'How to connect this bluetooth spea...,Aipmoz,"[Electronics, Camera & Photo, Video Surveillan...","{'Product Dimensions': '3.3 x 3.3 x 4 inches',...",B0CB1XQ9NR,NaN,NaN,NaN
4,All Electronics,"Military Smart Watch Men(Answer/Make Calls), 2...",4.0,136,[CUSTOMIZED FOR THE ADVENTURER: Our military s...,[],35.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'A tactical smartwatch for your out...,Moowhsh,"[Electronics, Wearable Technology, Smartwatches]",{'Product Dimensions': '9.84 x 8.66 x 0.79 inc...,B0BCF3KRMM,NaN,NaN,NaN

In [11]:
def preprocessed_decription(row):
    return f"{row['title']}{''.join(row['features'])}"

In [12]:
def extrect_first_large_image(row):
    return row['images'][0].get("large","")

In [13]:
df_items['description']=df_items.apply(preprocessed_decription,axis=1)
df_items['image']=df_items.apply(extrect_first_large_image,axis=1)

In [14]:
df_items

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,image
0,All Electronics,Gvoears Replacement Ear Pads Cushions for Skul...,4.6,129,[【Perfect Compatibility】These ear pads are mad...,Gvoears Replacement Ear Pads Cushions for Skul...,14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'the installation of earpads for sk...,G GVOEARS,"[Electronics, Headphones, Earbuds & Accessorie...",{'Product Dimensions': '3.94 x 3.15 x 0.98 inc...,B0BTBHYWY4,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41SY-3EDUy...
1,All Electronics,"Ethernet Splitter,NOBVEQ 1 Male to 2 Female Ne...",4.5,4654,[NOBVEQ RJ45 Ethernet Splitter: It converts th...,"Ethernet Splitter,NOBVEQ 1 Male to 2 Female Ne...",10.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],NOBVEQ,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '7.68 x 4.09 x 1.06 inc...,B0BWXS9QVY,NaN,NaN,NaN,https://m.media-amazon.com/images/I/31neVw1ZCt...
2,Cell Phones & Accessories,Case for iPad 9th Generation 10.2 Inch 2021 iP...,4.5,110,[【Compatibility】 - Designed for 10.2-Inch iPad...,Case for iPad 9th Generation 10.2 Inch 2021 iP...,33.90,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Case for iPad 9th/8th/7th generati...,H HOLIMET,"[Electronics, Computers & Accessories, Tablet ...",{'Package Dimensions': '10.16 x 7.87 x 0.75 in...,B0BYCT8F2V,NaN,NaN,NaN,https://m.media-amazon.com/images/I/516BZ2RJmS...
3,Camera & Photo,"Aipmoz Hidden Camera with 32G SD Card, Spy Cam...",4.8,107,[【Bluetooth Speaker Hidden Camera】This hidden ...,"Aipmoz Hidden Camera with 32G SD Card, Spy Cam...",89.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'How to connect this bluetooth spea...,Aipmoz,"[Electronics, Camera & Photo, Video Surveillan...","{'Product Dimensions': '3.3 x 3.3 x 4 inches',...",B0CB1XQ9NR,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41Qvn7tuwB...
4,All Electronics,"Military Smart Watch Men(Answer/Make Calls), 2...",4.0,136,[CUSTOMIZED FOR THE ADVENTURER: Our military s...,"Military Smart Watch Men(Answer/Make Calls), 2...",35.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'A tactical smartwatch for your out...,Moowhsh,"[Electronics, Wearable Technology, Smartwatches]",{'Product Dimensions': '9.84 x 8.66 x 0.79 inc...,B0BCF3KRMM,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41nCIVgk2u...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Cell Phones & Accessories,CYNOVA Insta 360 X3 Sticky Lens Guard Screen T...,3.9,188,[Insta360 x3 Lens Guard : Protection for both ...,CYNOVA Insta 360 X3 Sticky Lens Guard Screen T...,23.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Insta360 X3 Sticky Lens Guards', '...",CYNOVA,"[Electronics, Camera & Photo, Accessories, Dig...","{'Product Dimensions': '1""L x 1""W', 'Item Weig...",B0BJVCLHHW,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41yUJULN8L...
1996,Amazon Home,BulbaCraft 100Pcs Children Dental Stickers for...,4.5,174,[🦷Enjoy the High-Quality Vinyl Material - dent...,BulbaCraft 100Pcs Children Dental Stickers for...,8.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],BulbaCraft,"[Electronics, Computers & Accessories, Laptop ...","{'Brand': 'BulbaCraft', 'Room Type': 'Bathroom...",B0BPJJBNY2,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51sTRVI11w...
1997,Camera & Photo,"Rbcior Pet Camera, Indoor Camera Surveillance ...",4.3,106,[],"Rbcior Pet Camera, Indoor Camera Surveillance ...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Rbcior,[],{'Package Dimensions': '6.06 x 3.82 x 3.7 inch...,B09TP8231P,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41cSGzmsZi...
1998,Home Audio & Theater,"Phinistec 80GB HiFi MP3 Player with Bluetooth,...",3.8,101,[♪-【High-Fidelity Stereo Sound & DSD Codec】: T...,"Phinistec 80GB HiFi MP3 Player with Bluetooth,...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Phinistec,"[Electronics, Portable Audio & Video, MP3 & MP...",{'Product Dimensions': '4.02 x 2.36 x 0.55 inc...,B09WVFXZZ1,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41AIs1KrYy...
1999,All Electronics,"Saiyin Bluetooth Bookshelf Speakers, 40W X 2 P...",4.5,316,[𝐏𝐨𝐰𝐞𝐫𝐞𝐝 𝐁𝐥𝐮𝐞𝐭𝐨𝐨𝐭𝐡 𝐁𝐨𝐨𝐤𝐬𝐡𝐞𝐥𝐟 𝐒𝐩𝐞𝐚𝐤𝐞𝐫𝐬- Pair th...,"Saiyin Bluetooth Bookshelf Speakers, 40W X 2 P...",79.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Saiyin,"[Electronics, Home Audio, Speakers, Bookshelf ...",{'Product Dimensions': '11.8 x 9 x 6.7 inches'...,B0CB3PWNLC,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41byMhCYtb...

In [15]:
data_to_embed=df_items[["description","image","rating_number","price","average_rating","parent_asin"]].to_dict(orient="records")

In [16]:
data_to_embed[0]['description']

'Gvoears Replacement Ear Pads Cushions for Skullcandy Crusher Wireless, Crusher ANC/EVO, Hesh ANC/EVO, Hesh 3 Wireless, Also Fit for Skullcandy Venue Wireless ANC Headphone with Duable Leather Fabric【Perfect Compatibility】These ear pads are made specifically to fit the Skullcandy Hesh 3, Evo, and Crusher series of Headphones. You can comfortably upgrade your ear cushion for skullcandy crusher wireless over-ear headphones, hesh 3 wireless over-ear headphone, crusher evo/anc wireless over-ear headphones, hesh evo/anc wireless over-ear headphones, for skullcandy venue wireless over-ear headphone.【Durable&Comfortable】Crusher wireless replacement pads are designed with soft leather fabric to make your ears do not pain when you wear them for a long time. Durable design make Your headphone can be used for a long time. keep them comfortable and take care of your ears.【Noise Isolation】Earmuffs for skullcandy wireless constructed of premium memory foam, this headphone ear covers set insulates your ears with a perfect fit, preserving the original sound of the headset, improved comfort and enhance noise blocking, which brings you more quietness.【Easy to Install】 Just remove the old ear pads and put the new ear pads into the ear cups of the earphones, you can easily snap the ear pads into your earphones, Easy to install without any auxiliary tools.(Refer to the pictures/video for install steps)【Satisfaction Guarantee】 Package included:2 x for skullcandy crusher cushion( SIZE: 3.74inchx3.15inchx0.98inch), 4 x wipe pads,2 x earphone cable velcro. If you have any questions about earpads cushions replacement for skullcandy hesh 3, please feel free to contact us.'

In [17]:
text_to_embed=[data["description"] for data in data_to_embed]

In [18]:
embeddings = get_embedding_batch(text_to_embed)

In [21]:
len(embeddings[0])

1536

In [22]:
pointstructs=[]
i=1
for embedding,data in zip(embeddings,data_to_embed):
    if i==1:print(embedding,data)
    pointstructs.append(
        PointStruct(
            id=i,
            vector={
                "text-embedding-model-3-small":embedding,
                "bm25":Document(
                    text=data["description"],
                    model="qdrant/bm25"
                )
            },
            payload=data
        )
    )
    i+=1

[0.014129638671875, 0.0020885467529296875, 0.01305389404296875, 0.00627899169921875, -0.0390625, -0.039306640625, 0.0487060546875, 0.01971435546875, 0.026763916015625, -0.0552978515625, 0.0190582275390625, -0.01300811767578125, -0.0391845703125, 0.01412200927734375, -0.0023441314697265625, 0.0538330078125, 0.040985107421875, 0.006565093994140625, -0.01160430908203125, 0.008270263671875, -0.005741119384765625, 0.066650390625, 0.05224609375, 0.0103759765625, 0.041717529296875, 0.040740966796875, 0.01378631591796875, 0.0204010009765625, 0.054107666015625, 0.003719329833984375, -0.047210693359375, -0.0025482177734375, -0.006290435791015625, -0.05059814453125, -0.05450439453125, -0.003330230712890625, -0.02001953125, -0.0178985595703125, 0.00611114501953125, 0.008636474609375, 0.050689697265625, 0.01422882080078125, 0.0039520263671875, -0.0298919677734375, -0.0264129638671875, 0.026611328125, -0.031646728515625, 0.028839111328125, 0.001232147216796875, 0.0377197265625, 0.0103759765625, 0.03668212890625, -0.0235748291015625, 0.0278472900390625, -0.01342010498046875, -0.0171051025390625, 0.01294708251953125, -0.0245208740234375, -0.01029205322265625, -0.055419921875, -0.00978851318359375, -0.0244140625, 0.0186309814453125, -0.0172576904296875, 0.00868988037109375, 0.01360321044921875, 0.01158905029296875, 0.01342010498046875, -0.0157012939453125, -0.01241302490234375, 0.00943756103515625, 0.0312347412109375, -0.016265869140625, -0.0068511962890625, -0.00010508298873901367, 0.01255035400390625, 0.032501220703125, -0.0112152099609375, 0.025421142578125, 0.009552001953125, -0.05169677734375, 0.007404327392578125, -0.061767578125, 0.02294921875, -0.04443359375, -0.01177978515625, -0.06500244140625, -0.01314544677734375, -0.01357269287109375, 0.0023021697998046875, 0.022857666015625, -0.0007758140563964844, 0.006710052490234375, -0.036407470703125, -0.0352783203125, -0.0008325576782226562, -0.0263519287109375, -0.032867431640625, -0.01314544677734375, 0.032928466796875, 0.015625, -0.054840087890625, -0.041717529296875, -0.031982421875, 0.00829315185546875, -0.03143310546875, -0.040313720703125, -0.01873779296875, -0.029266357421875, 0.019012451171875, 0.035614013671875, -0.038482666015625, 0.0024261474609375, 0.00177001953125, -0.006275177001953125, 0.00034356117248535156, 0.04052734375, 0.00794219970703125, -0.0163116455078125, -0.016693115234375, -0.050933837890625, 0.0276641845703125, 0.044403076171875, -0.0498046875, -0.00914764404296875, 0.01479339599609375, 0.01171112060546875, 0.0047760009765625, -0.08984375, -0.018280029296875, 0.01186370849609375, 0.0037250518798828125, 0.050628662109375, -0.058624267578125, -0.025054931640625, -0.038665771484375, -0.02984619140625, 0.01995849609375, 0.004364013671875, 0.007049560546875, 0.00769805908203125, 0.007801055908203125, -0.03662109375, -0.0168609619140625, -0.0221710205078125, 0.008331298828125, 0.00638580322265625, -0.060089111328125, -0.0208282470703125, 0.05401611328125, -0.038116455078125, 0.01751708984375, -0.01451873779296875, 0.0034084320068359375, 0.0171356201171875, -0.0218505859375, 0.003818511962890625, 0.018646240234375, 0.00555419921875, -0.031829833984375, -0.0149078369140625, 0.0259246826171875, -0.009185791015625, -0.06201171875, 0.039276123046875, -0.0038127899169921875, -0.037017822265625, -0.0041351318359375, -0.0225067138671875, 0.019256591796875, 0.016357421875, -0.04620361328125, -0.0155792236328125, 0.041473388671875, 0.0276641845703125, -0.058685302734375, 0.0489501953125, 0.05853271484375, 0.0079345703125, 0.00783538818359375, 0.01580810546875, -0.0009160041809082031, 0.03485107421875, 0.03436279296875, 0.041961669921875, 0.00957489013671875, -0.0404052734375, 0.000804901123046875, -0.0149993896484375, -0.0205841064453125, 0.0390625, -0.0322265625, -0.04974365234375, 0.025909423828125, -0.025146484375, -0.0154571533203125, 0.0013341903686523438, -0.0357666015625, -0.004695892333984375, 0.0164337158203125, -0.046142578125, 0.012908935546875, 0.0175323486328125, 0.06219482421875, -0.0012493133544921875, -0.0175628662109375, -0.01447296142578125, 0.0355224609375, 0.0360107421875, 0.002834320068359375, 0.07073974609375, -0.0291900634765625, 0.00628662109375, 0.021820068359375, -0.01555633544921875, -0.0149688720703125, -0.0295867919921875, -0.00606536865234375, -0.0296478271484375, -0.006061553955078125, -0.0124359130859375, -0.0172576904296875, 0.037506103515625, 0.0299530029296875, -0.03363037109375, -0.01309967041015625, -0.0181121826171875, 0.01470184326171875, 0.007427215576171875, -0.006938934326171875, -0.00017499923706054688, 0.0653076171875, -0.019927978515625, 0.03546142578125, -0.00815582275390625, 0.01123046875, 0.0024814605712890625, -0.03363037109375, 0.03497314453125, -0.085205078125, -0.0181121826171875, -0.01383209228515625, -0.0301055908203125, 0.07403564453125, 0.001865386962890625, -0.0001055598258972168, -0.005702972412109375, -0.0352783203125, 0.035919189453125, 0.0411376953125, 0.00876617431640625, 0.017608642578125, 0.021697998046875, 0.036346435546875, 0.051910400390625, 0.00811767578125, 0.004100799560546875, 0.060577392578125, -0.05218505859375, -0.06304931640625, -0.006626129150390625, -0.01690673828125, -0.015777587890625, 0.04302978515625, 0.0311431884765625, -0.05682373046875, 0.032440185546875, 0.00519561767578125, -0.0316162109375, 0.01123809814453125, -0.01995849609375, 0.00968170166015625, -0.0016965866088867188, 0.00653076171875, 0.021636962890625, 0.02984619140625, -0.01806640625, -0.0288543701171875, -0.0187530517578125, 0.027740478515625, 0.0041961669921875, -0.04034423828125, -0.02081298828125, -0.0159149169921875, -0.0108642578125, 0.0035800933837890625, -0.035919189453125, 0.007965087890625, -0.01611328125, 0.01300811767578125, 0.025054931640625, -0.0576171875, -0.0231475830078125, -0.0237274169921875, -0.021453857421875, 0.0281524658203125, -0.00732421875, -0.02734375, -0.02569580078125, -0.05609130859375, 0.026947021484375, 0.043182373046875, 0.0021228790283203125, 0.064453125, -0.0489501953125, 0.019805908203125, 0.01419830322265625, 0.00032019615173339844, 0.0011262893676757812, -0.01532745361328125, -0.0364990234375, -0.007061004638671875, -0.0170745849609375, -0.0095367431640625, 0.0005192756652832031, -0.04473876953125, -0.0050201416015625, -0.038787841796875, -0.0021686553955078125, -0.07403564453125, -0.0008172988891601562, 0.01641845703125, 0.0023956298828125, -0.02825927734375, 0.044708251953125, 0.0146484375, 0.01885986328125, -0.0109710693359375, 0.0021877288818359375, -0.0194854736328125, -0.01313018798828125, -0.044952392578125, -0.0018911361694335938, -0.03173828125, -0.0095672607421875, 0.037811279296875, -0.037261962890625, -0.0173492431640625, -0.046295166015625, -0.0196533203125, -0.0115814208984375, -0.030853271484375, -0.04754638671875, -0.0199737548828125, -0.0062408447265625, -0.0017881393432617188, -0.0017995834350585938, 0.0283660888671875, -0.0011911392211914062, 0.051239013671875, -0.035125732421875, -0.00959014892578125, -0.022491455078125, -0.01479339599609375, -0.0023632049560546875, 0.0032024383544921875, 0.0009131431579589844, -0.04107666015625, -0.0241546630859375, 0.003940582275390625, 0.005657196044921875, 0.0310516357421875, -0.043121337890625, -0.0191802978515625, 0.0146026611328125, 0.0208587646484375, -0.0278472900390625, 0.02740478515625, 0.021728515625, 0.0023784637451171875, -0.00730133056640625, 0.0015468597412109375, -0.039093017578125, 0.01806640625, -0.06964111328125, 0.0136260986328125, -0.01422882080078125, -0.0183868408203125, -0.052490234375, -0.0640869140625, -0.002765655517578125, -0.01088714599609375, 0.018798828125, 0.006275177001953125, 0.01953125, 0.03143310546875, 0.0013704299926757812, 0.046630859375, -0.023468017578125, -0.0312042236328125, 0.037261962890625, 0.0020275115966796875, 0.005069732666015625, -0.0191802978515625, 0.034881591796875, 0.013580322265625, 0.06878662109375, -0.01398468017578125, 0.01097869873046875, 0.0262451171875, -0.032196044921875, -0.0205841064453125, 0.01261138916015625, -0.00502777099609375, -0.005107879638671875, -0.0023860931396484375, 0.03155517578125, 0.006866455078125, -0.006191253662109375, 0.00598907470703125, 0.0242156982421875, -0.03765869140625, 0.0063934326171875, 0.01397705078125, 0.012298583984375, 0.0020389556884765625, -0.038909912109375, -0.01433563232421875, 0.035614013671875, 0.00467681884765625, -0.00897216796875, -0.057281494140625, -0.03948974609375, 0.080810546875, 0.032012939453125, -0.0259246826171875, -0.0423583984375, -0.0309906005859375, 0.00902557373046875, -0.0163726806640625, -0.01922607421875, 0.0215301513671875, 0.00208282470703125, 0.0177764892578125, -0.0467529296875, 0.031951904296875, 0.033966064453125, 0.047149658203125, -0.022796630859375, 0.014801025390625, -0.0003349781036376953, -0.05029296875, 0.0236968994140625, 0.057098388671875, -0.04705810546875, 0.0460205078125, -0.0242462158203125, 0.0208892822265625, -0.058013916015625, 0.034210205078125, -0.0258636474609375, -0.00389862060546875, 0.007129669189453125, 0.0004572868347167969, 0.051605224609375, 0.00566864013671875, -0.04840087890625, 0.031951904296875, -0.0145263671875, 0.015625, 0.046722412109375, -0.02117919921875, 0.0274658203125, 0.00018012523651123047, -0.012054443359375, 0.0153961181640625, -0.022796630859375, 0.033477783203125, 0.00156402587890625, -0.04815673828125, 0.0450439453125, -0.0265655517578125, 0.0313720703125, 0.0005865097045898438, -0.005115509033203125, -0.044647216796875, -0.004383087158203125, -0.02410888671875, -0.040740966796875, -0.03326416015625, -0.0307464599609375, -0.033660888671875, -0.024200439453125, 0.0086822509765625, -0.01190185546875, 0.003444671630859375, 0.027801513671875, -0.04449462890625, -0.0242767333984375, -0.026092529296875, -0.021697998046875, 0.0024013519287109375, 0.006988525390625, -0.007762908935546875, 0.05194091796875, 0.0099334716796875, -0.0249481201171875, -0.0272216796875, -0.045013427734375, 0.0130767822265625, 0.0268402099609375, 0.002605438232421875, 0.03131103515625, 0.053741455078125, -0.03546142578125, 0.079345703125, -0.00266265869140625, 0.0286102294921875, 0.01045989990234375, 0.00673675537109375, 0.005443572998046875, 0.0247039794921875, -0.0162353515625, 0.0302886962890625, 0.010467529296875, -0.0229644775390625, 0.0011034011840820312, 0.0180816650390625, -0.0040130615234375, -0.008819580078125, -0.052825927734375, -0.0030345916748046875, 0.0234222412109375, -0.0243988037109375, -0.0172576904296875, -0.006378173828125, -0.046051025390625, -0.06341552734375, -0.033538818359375, -0.00885772705078125, -0.037628173828125, -0.0016527175903320312, -0.040191650390625, 0.007373809814453125, -0.011688232421875, 0.02227783203125, -0.01395416259765625, 0.01049041748046875, 0.006801605224609375, 0.03070068359375, -0.037445068359375, 0.0201263427734375, -0.026611328125, -0.042510986328125, 0.022369384765625, -0.014373779296875, -0.00970458984375, 0.0310516357421875, 0.0013675689697265625, -0.021453857421875, 0.004425048828125, 0.011932373046875, 0.03631591796875, 0.03277587890625, 0.009124755859375, 0.043182373046875, 0.0056304931640625, -0.036651611328125, 0.0477294921875, 0.0014200210571289062, 0.049102783203125, -0.003826141357421875, 0.0152435302734375, 0.039794921875, 0.00043845176696777344, 0.0369873046875, -0.0006070137023925781, 0.0279693603515625, -0.0142974853515625, -0.0127716064453125, 0.0246734619140625, -0.0305633544921875, 0.01056671142578125, -0.044097900390625, -6.258487701416016e-05, 0.0164947509765625, -0.0158233642578125, 0.0276031494140625, -0.0721435546875, 0.01332855224609375, -0.01995849609375, -0.01280975341796875, 0.007640838623046875, 0.033782958984375, -0.024749755859375, -0.026153564453125, 0.0088653564453125, 0.0234222412109375, 0.0032024383544921875, 0.0335693359375, -0.020782470703125, -0.0254669189453125, 0.009002685546875, -0.0205230712890625, 0.00586700439453125, 0.01261138916015625, -0.0087890625, 0.0309600830078125, 0.01210784912109375, -0.022552490234375, -0.004734039306640625, -0.024322509765625, 0.02227783203125, -0.01218414306640625, -0.006252288818359375, 0.025146484375, 0.0435791015625, -0.028656005859375, 0.018310546875, 0.039825439453125, 0.0140228271484375, -0.01555633544921875, -0.001316070556640625, -0.004558563232421875, -0.045257568359375, -0.00655364990234375, -0.002559661865234375, -0.0031185150146484375, 0.034088134765625, -0.0189361572265625, -0.039276123046875, -0.00482940673828125, 0.048614501953125, 0.0156402587890625, -0.01385498046875, 0.0081787109375, 0.0025482177734375, -0.005008697509765625, -0.0125885009765625, 0.033660888671875, 0.01910400390625, 0.03826904296875, -0.0126800537109375, -0.0389404296875, -0.017578125, -0.0252227783203125, -0.000720977783203125, -0.007671356201171875, -0.01727294921875, 0.0005393028259277344, -0.0249176025390625, 0.0035686492919921875, 0.00824737548828125, 0.006275177001953125, 0.00933074951171875, -0.0109405517578125, 0.0198974609375, 0.0066375732421875, 0.0257415771484375, -0.0184783935546875, 0.01020050048828125, 0.003551483154296875, 0.00286865234375, -0.0218048095703125, 0.0243682861328125, 0.03515625, -0.0232086181640625, 0.0074615478515625, 0.01207733154296875, -0.038970947265625, -0.0207366943359375, 0.02459716796875, 0.005680084228515625, -0.0139007568359375, -0.004852294921875, 0.0006999969482421875, 0.050323486328125, 0.0029888153076171875, -0.0026702880859375, 0.006702423095703125, -0.0167999267578125, 0.00838470458984375, 0.0654296875, 0.0202484130859375, 0.051605224609375, 0.00119781494140625, 0.0003743171691894531, 0.00896453857421875, 0.0301055908203125, 0.0005745887756347656, 0.002696990966796875, -0.01397705078125, 0.00861358642578125, -0.0382080078125, 0.003055572509765625, 0.0008172988891601562, 0.0005316734313964844, -0.044525146484375, -0.032318115234375, 0.0036487579345703125, -0.01555633544921875, 0.019683837890625, -0.0205841064453125, -0.006229400634765625, 0.008056640625, 0.01302337646484375, 0.004306793212890625, -0.052490234375, 0.034271240234375, 0.018585205078125, -0.0036678314208984375, 0.0113525390625, -0.015716552734375, -0.0218505859375, -0.041656494140625, 0.0127716064453125, -0.0254974365234375, 0.0110931396484375, 0.0192108154296875, -0.003101348876953125, -0.0166168212890625, -0.006923675537109375, -0.00809478759765625, 0.0124969482421875, 0.001468658447265625, 0.0004782676696777344, 0.01297760009765625, 0.00281524658203125, 0.011077880859375, 0.00952911376953125, 0.004596710205078125, 0.032623291015625, -0.0176544189453125, -0.0043792724609375, -0.035369873046875, 0.01690673828125, -0.0260009765625, 0.00991058349609375, -0.04632568359375, -0.00868988037109375, -0.048736572265625, 0.024017333984375, 0.041229248046875, 0.006893157958984375, -0.01433563232421875, -0.01061248779296875, -0.046356201171875, -0.0014934539794921875, -0.034912109375, -0.0236053466796875, 0.0015850067138671875, -0.010101318359375, 0.0194244384765625, -0.00901031494140625, 0.003726959228515625, 0.008880615234375, 0.01477813720703125, 0.017303466796875, 0.0272674560546875, -0.0213775634765625, -0.024871826171875, 0.005889892578125, -0.025299072265625, 0.00821685791015625, 0.027862548828125, -0.01561737060546875, -0.00183868408203125, -0.006443023681640625, 0.0251617431640625, -0.040618896484375, 0.03851318359375, 0.029937744140625, -0.0355224609375, 0.0002677440643310547, 0.0102386474609375, 0.007843017578125, -0.0662841796875, 0.0056915283203125, -0.031768798828125, 0.022003173828125, 0.0261077880859375, -0.00012755393981933594, -0.006923675537109375, -0.023712158203125, 0.003475189208984375, -0.018585205078125, -0.0204315185546875, -0.01215362548828125, -0.041046142578125, 0.0038604736328125, -0.0290069580078125, -0.0007266998291015625, 0.05413818359375, 0.00983428955078125, -0.038055419921875, -0.04327392578125, -0.005741119384765625, -0.0091552734375, 0.005176544189453125, 0.0006756782531738281, -0.044586181640625, -0.007354736328125, 0.0179290771484375, -0.032318115234375, -0.01410675048828125, -0.0161895751953125, 0.0215301513671875, 0.005863189697265625, 0.0024623870849609375, 0.05767822265625, -0.0439453125, 0.0156402587890625, 0.00815582275390625, -0.0308074951171875, 0.024322509765625, 0.0214080810546875, -0.0307159423828125, 0.0256195068359375, 0.0247039794921875, -0.007099151611328125, -0.0144805908203125, 0.007671356201171875, -0.034698486328125, -0.0352783203125, 0.057525634765625, 0.004039764404296875, 0.0009236335754394531, 0.0060272216796875, 0.004314422607421875, 0.056610107421875, -0.016265869140625, -0.020416259765625, 0.010040283203125, 0.0034580230712890625, -0.02899169921875, -0.0223541259765625, 0.04034423828125, -0.02569580078125, -0.00757598876953125, -0.040740966796875, 0.02215576171875, 0.00872039794921875, 0.050445556640625, -0.006805419921875, 0.006549835205078125, 0.02978515625, -0.0112762451171875, 0.05035400390625, 0.0081634521484375, -0.022552490234375, 0.023162841796875, -0.0400390625, 0.035491943359375, 0.01212310791015625, 0.006317138671875, 0.0187835693359375, 0.04449462890625, -0.024566650390625, -0.001556396484375, 0.006626129150390625, 0.006710052490234375, -0.0203704833984375, -0.00675201416015625, 0.049835205078125, 0.0189361572265625, 0.0032138824462890625, -0.036163330078125, 0.0155029296875, -0.0255126953125, -0.008819580078125, -0.03277587890625, -0.0297088623046875, 0.00012409687042236328, -0.0255584716796875, 0.00811767578125, -0.00423431396484375, -0.0201263427734375, -0.04473876953125, 0.0186309814453125, -0.02874755859375, -0.03253173828125, 0.0231170654296875, 0.00494384765625, 0.00421142578125, 0.025543212890625, 0.0341796875, 0.047210693359375, 0.07318115234375, 0.036468505859375, -0.0215911865234375, -0.041717529296875, -0.01375579833984375, -0.01898193359375, -0.009429931640625, -0.00164031982421875, 0.026153564453125, 0.00783538818359375, 0.0174102783203125, -0.0082550048828125, -0.009033203125, -0.004817962646484375, -0.0016775131225585938, 0.0141754150390625, 0.036224365234375, -0.04449462890625, 0.03570556640625, 0.00019538402557373047, 0.036834716796875, -0.004825592041015625, 0.015777587890625, -0.0308380126953125, -0.043731689453125, -0.0313720703125, -0.01473236083984375, 0.0239715576171875, 0.000762939453125, 0.032928466796875, 0.00910186767578125, -0.037872314453125, 0.036865234375, 0.019927978515625, -0.0162811279296875, 0.00579071044921875, -0.01532745361328125, -0.0265045166015625, -0.0208282470703125, -0.06158447265625, -0.004764556884765625, 0.0232086181640625, -0.01122283935546875, -0.00920867919921875, 0.0005922317504882812, -0.007328033447265625, -0.00830078125, 0.0233001708984375, -0.0015344619750976562, 0.012908935546875, 0.011199951171875, 0.040283203125, 0.0293121337890625, -0.01357269287109375, -0.03277587890625, 0.00534820556640625, 0.015228271484375, 0.01263427734375, 0.0289154052734375, 0.01158905029296875, -0.0014324188232421875, -0.0093536376953125, 0.0019550323486328125, -0.0158538818359375, -0.0345458984375, 0.03387451171875, 0.0057525634765625, 0.042724609375, -0.024444580078125, -0.00258636474609375, -0.005016326904296875, -0.021026611328125, -0.018157958984375, -0.01317596435546875, 0.015777587890625, 0.06109619140625, -0.00806427001953125, 0.0201263427734375, -0.0236663818359375, -0.00872802734375, 0.009063720703125, -0.0101470947265625, 0.0185546875, 0.003437042236328125, -0.014801025390625, -0.0285491943359375, -0.011260986328125, 0.0087432861328125, 0.051544189453125, -6.246566772460938e-05, 0.0131072998046875, 0.01343536376953125, 0.0161590576171875, 0.001377105712890625, 0.024444580078125, 0.026702880859375, 0.0028285980224609375, -0.00860595703125, -0.006313323974609375, 0.01580810546875, -0.03607177734375, -0.01000213623046875, 0.0140533447265625, 0.05712890625, 0.0367431640625, 0.013580322265625, 0.006404876708984375, 0.0159149169921875, 0.0032215118408203125, 0.00988006591796875, 0.002391815185546875, 0.032440185546875, 0.0211181640625, 0.01030731201171875, -1.6987323760986328e-05, -0.007289886474609375, 0.00994110107421875, 0.00881195068359375, 0.0248565673828125, 0.0222

In [23]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    points=pointstructs[0:500],
    wait=True
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

In [24]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    points=pointstructs[500:1000],
    wait=True
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

In [25]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    points=pointstructs[1000:1500],
    wait=True
)

UpdateResult(operation_id=3, status=<UpdateStatus.COMPLETED: 'completed'>)

In [26]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    points=pointstructs[1500:2000],
    wait=True
)

UpdateResult(operation_id=4, status=<UpdateStatus.COMPLETED: 'completed'>)

In [27]:
client=OpenAI()

In [7]:
def get_embedding(text,model="text-embedding-3-small"):
    response=client.embeddings.create(
        model=model,
        input=text
    )
    return response.data[0].embedding

In [5]:
def reteriver_data(query, quadrant_client, k):
    query_embedding = get_embedding(query)

    result = quadrant_client.query_points(
        collection_name="Amazon-items-collection-02-hybrid-serach",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-model-3-small",
                limit=20
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )

        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_rating = []
    retrieved_image_urls = []
    retrieved_prices = []

    for point in result.points:
        payload = point.payload or {}
        retrieved_context_ids.append(payload.get("parent_asin"))
        retrieved_context.append(payload.get("description", ""))
        retrieved_context_rating.append(payload.get("average_rating"))
        similarity_scores.append(point.score)
        retrieved_image_urls.append(payload.get("image", ""))
        retrieved_prices.append(payload.get("price"))

    return (
        retrieved_context,
        retrieved_context_ids,
        retrieved_context_rating,
        similarity_scores,
        retrieved_image_urls,
        retrieved_prices
    )

In [10]:
result=reteriver_data("can i get some earphones",qdrant_client,k=10)

In [15]:
result

(['Wireless EarbudsWireless Earbuds.Wireless Earbuds.Wireless Earbuds.Wireless Earbuds.Wireless Earbuds.',
  'Cleaner Kit for AirPod Pro 1 2 3, AMEAMI Earbud Cleaning Pen Tool for iPhone Samsung Lego Huawei MI Wireless Headphone (White)🔴【SEPARATED DUAL HEAD DESIGN】3-in-1 airpods cleaning kit with Flocking Sponge, High-density Brush and Metal Pen Tip, meet a variety of cleaning airpods, earbuds, headphone, earphone, case needs🔴【HIGH-DENSITY BRUSH & FLOCKING SPONGE】There are a soft microfiber brush and a lightweight flocking sponge above the cleaning pen, which can deeply clean the small parts, holes and charging bin of the AirPods. It is beneficial to improve headphones sound quality, charging efficiency and prolong service life.🔴【METAL CLEANER PEN TIP】Metal cleaning pen tip can clean the stubborn dust, thoroughly clean the gap.🔴【PERFECT COMBINATION】You will get a 3-in-1 airpod cleaning kit and 6 pieces of wet & dry wipe. It will keep your airpods or wireless headphones as clean as possible. This combination is the result of our survey of 1000+ airpods users.🔴【WIDE RANGE APPLICATION】This cleaning pen can not only clean the earphones, but also the earphone charging box, mobile phone earpieces, microphones, etc. compatible with most Bluetooth earphones on the market.',
  'Jesebang Wireless Earbud, Bluetoth 5.2 Headphones Built-in HD Mic, 13mm Bluetoth Earphones with 60ms Ultra-Low Latency, 40H Playtime Compatible with iOS, Android, IP7 Waterproof Touch Control, Black…Bluetoth 5.2 Technology: Jesebang Bluetoth earbud with advanced bluetooth 5.2 technology owns fast and stable transmission without tangling, which makes the wireless earbud connect to electronic devices more consistently, providing you with an uninterrupted calling and music experience.Power Display and Type-C Quick Charge: Wireless headphones features with smart LED light display, you can easily know the battery consumption on both bluetoth earphones and the charging case. Besides, equipped with Type-C cable to fully charge the rechargerable case only 1.5 Hours. Quick charging technology enables 2 hours of listening from just 20 minutes of charge.Immersive Stereo Sound: These wireless earphones with 13mm speakers and triple-layer composite diaphragms provide powerful bass, stunning treble and clear mids. These earbud are designed for sound and music lovers.Superior Clear Call: IT100 Bluetoth earphones support the mono mode and twin stereo mode, you can share the earphones with your friends and families. Each earbud has a build-in microphone for phone calls. ENC noise reduction can make others hear your voice very clearly while phone calls.Super Portable Charging Case with 40H Playtime: The earbud can be used for 8 hours after a single charge. The built-in 400mAh lithium battery in the charging case can charge the bluetoth earbud more than 4 times, and the total playtime life can reach 40 hours. A single earphones weighs only 4.1g and the weight of the charging case is only 47g, it’s very portable when going out for work and travel.Customizable Fit : The earphones every surface that touch your ear is made of 30° soft rubber. The liquid soft rubber nozzle spreads pressure evenly across your ear for comfort, stability, and passive noise blocking. Giving you a fit for all-day comfort with less fatigue.IP7 Waterproof: IP7 waterproof prevents ordinary splashing water and rain. Enjoy sports and outdoor activities without worrying about getting wet or sweaty.',
  'ZTOZ Wireless Earbuds Bluetooth 5.0 Headphones with Immersive Bass Sound, Mini Charging Case, Waterproof Earphones for Sport/Work, Headsets Compatible with iPhone/Android/PC, (White)【ENC Noise Cancellation】- The wireless Bluetooth earbuds use dual-mic noise reduction technology, which reduces environmental noise, picks up human voice, and provides a clear voice.【Balanced Stereo Dynamic Earphones】- Wireless Bluetooth earphones use a 13mm dynamic vibration unit and high-definition audio coding technology. Earphones have balanced stereo for mid-to-high frequency, and also have dynamic deep bass.【Touch Control & 30H Playtime】- Wireless Bluetooth earphones with single charging can play for 5 hours and the charging case could offer 5-6 times charging. Just touch the controlling area of the earbuds lightly to pause/play music and the previous/next.【Ergonomic Design Headphone】- Lightweight design fit comfortably and snuggly in your ear for all-day wearing with no pain; it is suitable for most people. They fit securely for daily office work or sports, no more worry about earbuds falling out.【Delivered by Amazon】- You have made an excellent decision by choosing our product. We offer a 365-day free warranty on every product. If you have any questions about our products, please don’t hesitate to contact us. We are at your service 24 hours a day, 7 days a week.',
  'Wireless Earbuds Sport,Bluetooth 5.1 Earphones Earhook,HD Stereo, Touch Control, USB-C & Wireless Charging,45H Playtime, Bluetooth Earbuds Sport IPX7,in Ear Headphones Mic for Sports Running Workout45 Hours of Playtime:Sport earbuds bluetooth can provide up to 7.5 hours of playtime, and the charging case can provide additional 5 charges, so that the total playtime reaches 45 hours which provides impressive music enjoy all-day.USB-C Quick & Wireless Charging: You can use the USB type-c cable to get quick wired charging, only 10 minutes of charging gets you 1.5 hours of use. The portable case also supports wireless charging for easy charge, so you can also simply lay the case on a wireless charger (sold separately) for convenient wireless charging.Smart Touch Control: Zeussa R1 offers advanced touch control allowing phone-free control of play, pause, mute, volume and track settings and can even active Siri and Google assistants, with the controls easily activated and changed by a simple touch to the earbuds.Bluetooth 5.1: Sport Earbuds blurtooth use the most advanced Bluetooth 5.1 technology, which can achieve uninterrupted fast transmission and low latency. No matter if it is games, calls or sports, there is no need to worry about signal interruption.IPX7 Waterproof: Sport earphones bluetooth wireless has an advanced nano coating waterproof function, which can prevent rain or sweat from splashing, and is suitable for wearing in any sports.',
  'ELECDER i45 On-Ear Headphones with Microphone - Foldable Stereo Bass Headphones with No-Tangle 1.5M Cord, 3.5MM Jack, Portable Wired Headphones for School/Kids/Teens/Smartphones/Travel/Tablet - Red【Immersive Hi-Fi Stereo Bass】 Built-in a 40mm audio driver to ensure rich bass and crisp midrange which provides the best sound reproduction for all your needs, while ideal sound isolation effect to eliminate annoying background noise.【Lightweight and Folding】 Padded ultra-soft ear cushions and headband provide a perfect custom fit for all users and a comfortable and Long-lasting listening experience while protecting the ears. Adjustable size slider and foldable design make it Space-Saving and easy to carry.【Durable and Tangle-free】 The rugged resilient plastic shell and no tangle 4.9 ft (1.5m) nylon woven rope ensure durability. Wired headphones are suitable for kids, children, adults, and are designed for school, online learning, training, home, office, Airport, Plane, Travel, and more.【Friendly Microphone Button】 Easy to answer or end calls, Play/Pause audio, and skip tracks forward and backward via in-line control. Wired headphones offer universal compatibility with all 3.5mm jack devices, such as smartphones, laptops, desktops, Kindle, computers, PCs, MP3, MP4, etc.【What You Get】 Elecder i45 headphones wired, user guide, our worry-free 24-month warranty, easy to contact and friendly customer service.',
  'YINYOO KBEAR Rosefinch in Ear Earphones Headphones, Wired Earbuds with Microphone with Clear Sound Detachable Cable 3.5mm Plug for Computer, Smartphone, PC, Calling, Home (Black, with mic)▶ 【Good sound quality】 Based on the Harman Curve, the tuning of Rosefinch has enhanced the atmosphere and quantity of bass to present a more dynamic and thicker sound signature.The Unit owns low impedance and high sensitivity, Mobile phones can also be easily pushed directly. Bring you a new kind of sense.▶ 【3.5mm plug, compatible cable】 Professional 4 core OFC wire soft and durable. The 3.5mm plug can work with all 3.5mm related devices, Androids, smartphones,pc, phones, MP3/MP4 players, music speakers.▶ 【Detachable 2pins 0.78mm Connector】The detachable design improves the playability, lets you can exchange other HiFi cables. Search yinyoo cable, discover more HIFI cables, find what you want.▶ 【One-button line control, fast and convenient】 The in-line microphone sits just below the jaw, picks up your voice, which ensures clear phone call conversations. With the remote buttons, you can easily answer/end calls, pause/play/skip musics. (volume control not supported )▶ 【 Noise isolation】 Properly wear earbuds can effective reduce noise. Effectively more reduce external noise interference after being worn tightly, then you can just enjoy music by adjusting low volume.▶ 【The comforts you were looking for】 Ergonomic design and ear Hook provide you comfortable wearing experience, Wrap-around ear design keeps earbuds from slipping out while working out. The memory ear hook can hold its shape around the ear.▶ 【Listen anytime and anywhere】Suitable for work, study, calling, running, releaxing, workout, gaming, stage, outing, show, and other scenes. Suits listening to the rock the pop and so on. and also perfect for school,home,Christmas,Thanksgiving day,Halloween,Black Friday,Family,Gift,Young,Student,Boy,girl.▶ 【What will you get?】Package includes 1 pair kbear rosefinch headset, 1* earphones cable, 3 pairs of silicone ear tips. and one user manual.▶ 【12 MONTHS-WARRANTY】You will get one year protective time and friendly customer service from the date of purchase. if there are any questions,problem, issues, pls feel free to contact us, we will give you a reply asap and provide solution. Wish you a happy shopping~Thank again!',
  'iFory USB C Headphones, Hi-Res Type C Earphones in-Ear Earbud with Baried Suit with Microphone and Volume Control Compatible with Google Pixel LG Samsung Oneplus Sony MacBook Black…【Wide Compatibility】-The USB C earphones compatible with Samsung Galaxy S21, Ultra, S21 Plus, S21, Note 20 Ultra, OnePlus 9, Google Pixel 5, Sony Xperia, VIVO Y20s, iPad mini 6 2021,iPad Pro,Macbook Pro,Macbook Air,iPad Air 4th&5th gen, and other Type C device without 3.5mm port.【Built-in Mic & Volume Control】- The USB C headphones feature the Microphone and three-button controllers. It allows you to play/pause songs, skips the next/previous song without picking up your phone, easily access volume control during usage; The high-quality microphone which can hand-free calling, allow you to easily answer/end calls.【Hi-Res Sound Quality】- iFory Type C Hi-Res wired earbuds adopt the latest DAC chip to provide high-quality sound and a solid connection by converting standard resolution music to superior clear audio.These improvements greatly extend the life of wired headphones and give you a wider sound range and better bass than traditional 10mm speakers.【Ergonomic Headphone Design】the ergonomically built and ultra-lightweight in-ear earphone fit the ear perfectly without any pain even wearing them all day long. With a durable design with high-quality materials, each wire have inside oxygen-free copper wire technology and sweat proof making it perfect for daily use. And it could also reduce the sound of the surrounding environment about 30db.【Super Durable Quality Material】high quality in materials inside each wire have inside oxygen-free copper wire technology, Nylon cable suit stretch resistant, long-lasting; 1.1 meters length, nylon braided cord, got through 8000+ bend bears test, which is durable for daily usage. Easy for carrying, you can enjoy music with it wherever and whenever.',
  'PocBuds Wireless Earbuds Sports Headphones Headset with Charging Case90Hrs Playtime with 2200mAh Charging Case: Bluetooth headphones are equipped with a 75mAh battery to get 10 hours of music from a single charge of the workout earbuds. Add an extra 8 full recharges up to 90 hours of listening time combined with the included charging case. More than 2 hours playtime with a 15-minute quick charge on the go, so you can keep your music going with no interruptions at all. (10-12hrs in buds with 60%-80% volume)Dual LED Digital Display: Wireless earbuds with digital screen show the remaining power of the charging case by the left number and the charging status of the ear buds by the right LED light bar, which can intuitively reflect real time power to ensure timely charging and embody the sense of technology. The case presents its battery levels from 1 to 100. Once earphones are placed back into the charging case, which will begin to charge, and stop flashing until fully charged.Immersive Audio Experience & Crystal Clear Calls: Wireless headphones features an 11mm speaker with dual-chamber acoustic drivers for bass and crisp stereo sound that will immerse you in your music and give you a private concert listening experience. The built-in dual beam forming microphone target your voice and filter partial noise, which allowing you to catch every word of the call and have a great conversation without take the bluetooth earphones off.One-step Pairing & Dual Audio Control: Bluetooth earphones are easy and fast to pair with your device by opening the charging case and taking earbuds out. Ear phones compatible with mobile phones and any devices with Bluetooth-enabled. Multi-functional physical and volume control button are sturdy and responsive, no worry of accidental touching. Bluetooth connectivity can be maintained within 30 feet which can free your hands to easily control audio play and calls without operating your phone.Designed for Sports & IPX7 Sweatproof: Bluetooth earbuds are ergonomically designed with flexible earhooks and three different sizes of silicone eartips so that wireless earphones can fit your ears comfortably. No need to worry about shifting or falling out, they will stay in place even when doing exercise. IPX7 sweatproof can effectively resist sweat and rain without worrying about damaging the headphones, perfect for your workout, gym or running. The charging case is not waterproof.Support Wireless & Type-C Charging: The charging case for headphones wireless bluetooth supports wireless and Type-C charging, which make charging more convenient. Wireless charging gets rid of the cable and simply keeps the LED display facing up on top of any Qi-certified charging mat (not included). Type-C charging just use the included USB-C cable and a charging adapter (not included) to charge. Fully charge the charging case takes 3 hours via Type-C cable or about 6 hours via charging mat.',
  'occiam Wireless Earbuds Bluetoth Headphones 48H Play Back Earphones in Ear TWS Waterproof with Microphone LED Display for Sports Running Workout GreenLED Power Display for Charging Case. Occiam sports bluetoth headphones charging case with led power Display shows remaining power in percentage.Charging case presents its battery from 1% to 100%. For the right or the left true wireless earbuds, while the earbud is chariging, the led bars of the earbud will flash, once the earbud are fully charged, the led bars of the earbud have no light flashing.48Hrs Battery Life with Charging Case. Built in 600mAh charging case. The both earbuds can last for 8Hours music time on a single 1.5hours charge. The charging case can charge the twin sports earbuds for 6 times, with the portable charging case you will get 48hrs playing music.Engineered design for sports. Adjustable and secure fit silicone ear hooks and ergonomic design ensure the sports earbuds stay comfortably firm in place when doing sports, running,other outside activity etc.Equipped with 3 pairs of different sizes of spare ear caps for options. Even do strenuous exercise, the earbuds will not fall off. And IPX5 splashproof protects the sports wireless earphones from water drop or sweat damageOne Step Auto Pairing. Picking up occiam sports Earphones from charging case,they will power on and pair with each other automatically.Then active mobile phone bluetoth to search “T17” to connect. After the first successful connection,the sports earbuds will automatically connect to the last paired device when reboot.When using single earphone, just take out the second one to achieve seamless transformation between single mode and twin mode.Sound Quality. The microphones of earbuds reduce background noise,make phone calls from stable signal and low power consumption.Each sport earbud has buttons to control the function of answer and reject phone, volume adjustment,switch music ,voice assisatant. Stereo sound,handsfree calling during sports anytime and anywhere.'],
 ['B09PG1T4L8',
  'B0B2757LDP',
  'B09XM5MDZH',
  'B09Y8NHSH2',
  'B09WHCYXGT',
  'B0B2R7WJMD',
  'B087CV5K43',
  'B09TDBTSNF',
  'B0BRXXVDSW',
  'B08Y8QFQGM'],
 [3.3, 4.3, 4.0, 3.5, 3.9, 4.5, 4.4, 4.3, 4.5, 4.3],
 [0.5,
  0.5,
  0.33333334,
  0.33333334,
  0.25,
  0.25,
  0.21666667,
  0.2,
  0.2,
  0.16666667],
 ['https://m.media-amazon.com/images/I/31Zl9fjbQDL._AC_.jpg',
  'https://m.media-amazon.com/images/I/41UU3+gosgL._AC_.jpg',
  'https://m.media-amazon.com/images/I/41+hOqwRtOL._AC_.jpg',
  'https://m.media-amazon.com/images/I/31pJuQkT7dL._AC_.jpg',
  'https://m.media-amazon.com/images/I/41BmtE1U+wL._AC_.jpg',
  'https://m.media-amazon.com/images/I/4162cfpcAXL._AC_.jpg',
  'https://m.media-amazon.com/images/I/414fjefXE7L._AC_.jpg',
  'https://m.media-amazon.com/images/I/311dv5JI7DL._AC_.jpg',
  'https://m.media-amazon.com/images/I/417MBk0dpDL._AC_.jpg',
  'https://m.media-amazon.com/images/I/41xd6QKUQpL._AC_.jpg'],
 [None, 8.99, None, None, None, 16.99, 23.99, 19.99, None, None])

In [11]:
CO_API_KEY=os.getenv("CO_API_KEY")

In [12]:

cohere_client=cohere.ClientV2(CO_API_KEY)

In [17]:
response_rerank=cohere_client.rerank(
    model= "rerank-v4.0-fast",##"rerank-v4.0-pro",
    query="can i get some earphones",
    documents=result[0],
    top_n=10
)

In [23]:
response_rerank.results[0].index

6

In [24]:
reranked_products = []

for item in response_rerank.results:
    idx = item.index

    reranked_products.append({
        "product_id": result[1][idx],
        "rating": result[2][idx],
        "fusion_score": result[3][idx],
        "image": result[4][idx],
        "price": result[5][idx],
        "description": result[0][idx],
        "rerank_score": item.relevance_score,
    })

In [25]:
reranked_products

[{'product_id': 'B087CV5K43',
  'rating': 4.4,
  'fusion_score': 0.21666667,
  'image': 'https://m.media-amazon.com/images/I/414fjefXE7L._AC_.jpg',
  'price': 23.99,
  'description': 'YINYOO KBEAR Rosefinch in Ear Earphones Headphones, Wired Earbuds with Microphone with Clear Sound Detachable Cable 3.5mm Plug for Computer, Smartphone, PC, Calling, Home (Black, with mic)▶ 【Good sound quality】 Based on the Harman Curve, the tuning of Rosefinch has enhanced the atmosphere and quantity of bass to present a more dynamic and thicker sound signature.The Unit owns low impedance and high sensitivity, Mobile phones can also be easily pushed directly. Bring you a new kind of sense.▶ 【3.5mm plug, compatible cable】 Professional 4 core OFC wire soft and durable. The 3.5mm plug can work with all 3.5mm related devices, Androids, smartphones,pc, phones, MP3/MP4 players, music speakers.▶ 【Detachable 2pins 0.78mm Connector】The detachable design improves the playability, lets you can exchange other HiFi cables. Search yinyoo cable, discover more HIFI cables, find what you want.▶ 【One-button line control, fast and convenient】 The in-line microphone sits just below the jaw, picks up your voice, which ensures clear phone call conversations. With the remote buttons, you can easily answer/end calls, pause/play/skip musics. (volume control not supported )▶ 【 Noise isolation】 Properly wear earbuds can effective reduce noise. Effectively more reduce external noise interference after being worn tightly, then you can just enjoy music by adjusting low volume.▶ 【The comforts you were looking for】 Ergonomic design and ear Hook provide you comfortable wearing experience, Wrap-around ear design keeps earbuds from slipping out while working out. The memory ear hook can hold its shape around the ear.▶ 【Listen anytime and anywhere】Suitable for work, study, calling, running, releaxing, workout, gaming, stage, outing, show, and other scenes. Suits listening to the rock the pop and so on. and also perfect for school,home,Christmas,Thanksgiving day,Halloween,Black Friday,Family,Gift,Young,Student,Boy,girl.▶ 【What will you get?】Package includes 1 pair kbear rosefinch headset, 1* earphones cable, 3 pairs of silicone ear tips. and one user manual.▶ 【12 MONTHS-WARRANTY】You will get one year protective time and friendly customer service from the date of purchase. if there are any questions,problem, issues, pls feel free to contact us, we will give you a reply asap and provide solution. Wish you a happy shopping~Thank again!',
  'rerank_score': 0.69562757},
 {'product_id': 'B09XM5MDZH',
  'rating': 4.0,
  'fusion_score': 0.33333334,
  'image': 'https://m.media-amazon.com/images/I/41+hOqwRtOL._AC_.jpg',
  'price': None,
  'description': 'Jesebang Wireless Earbud, Bluetoth 5.2 Headphones Built-in HD Mic, 13mm Bluetoth Earphones with 60ms Ultra-Low Latency, 40H Playtime Compatible with iOS, Android, IP7 Waterproof Touch Control, Black…Bluetoth 5.2 Technology: Jesebang Bluetoth earbud with advanced bluetooth 5.2 technology owns fast and stable transmission without tangling, which makes the wireless earbud connect to electronic devices more consistently, providing you with an uninterrupted calling and music experience.Power Display and Type-C Quick Charge: Wireless headphones features with smart LED light display, you can easily know the battery consumption on both bluetoth earphones and the charging case. Besides, equipped with Type-C cable to fully charge the rechargerable case only 1.5 Hours. Quick charging technology enables 2 hours of listening from just 20 minutes of charge.Immersive Stereo Sound: These wireless earphones with 13mm speakers and triple-layer composite diaphragms provide powerful bass, stunning treble and clear mids. These earbud are designed for sound and music lovers.Superior Clear Call: IT100 Bluetoth earphones support the mono mode and twin stereo mode, you can share the earphones with your friends and families. Each earbud has a build-in microphone for phone calls. ENC noise reduction can make others hear your voice very clearly while phone calls.Super Portable Charging Case with 40H Playtime: The earbud can be used for 8 hours after a single charge. The built-in 400mAh lithium battery in the charging case can charge the bluetoth earbud more than 4 times, and the total playtime life can reach 40 hours. A single earphones weighs only 4.1g and the weight of the charging case is only 47g, it’s very portable when going out for work and travel.Customizable Fit : The earphones every surface that touch your ear is made of 30° soft rubber. The liquid soft rubber nozzle spreads pressure evenly across your ear for comfort, stability, and passive noise blocking. Giving you a fit for all-day comfort with less fatigue.IP7 Waterproof: IP7 waterproof prevents ordinary splashing water and rain. Enjoy sports and outdoor activities without worrying about getting wet or sweaty.',
  'rerank_score': 0.67542213},
 {'product_id': 'B09Y8NHSH2',
  'rating': 3.5,
  'fusion_score': 0.33333334,
  'image': 'https://m.media-amazon.com/images/I/31pJuQkT7dL._AC_.jpg',
  'price': None,
  'description': 'ZTOZ Wireless Earbuds Bluetooth 5.0 Headphones with Immersive Bass Sound, Mini Charging Case, Waterproof Earphones for Sport/Work, Headsets Compatible with iPhone/Android/PC, (White)【ENC Noise Cancellation】- The wireless Bluetooth earbuds use dual-mic noise reduction technology, which reduces environmental noise, picks up human voice, and provides a clear voice.【Balanced Stereo Dynamic Earphones】- Wireless Bluetooth earphones use a 13mm dynamic vibration unit and high-definition audio coding technology. Earphones have balanced stereo for mid-to-high frequency, and also have dynamic deep bass.【Touch Control & 30H Playtime】- Wireless Bluetooth earphones with single charging can play for 5 hours and the charging case could offer 5-6 times charging. Just touch the controlling area of the earbuds lightly to pause/play music and the previous/next.【Ergonomic Design Headphone】- Lightweight design fit comfortably and snuggly in your ear for all-day wearing with no pain; it is suitable for most people. They fit securely for daily office work or sports, no more worry about earbuds falling out.【Delivered by Amazon】- You have made an excellent decision by choosing our product. We offer a 365-day free warranty on every product. If you have any questions about our products, please don’t hesitate to contact us. We are at your service 24 hours a day, 7 days a week.',
  'rerank_score': 0.67026305},
 {'product_id': 'B09WHCYXGT',
  'rating': 3.9,
  'fusion_score': 0.25,
  'image': 'https://m.media-amazon.com/images/I/41BmtE1U+wL._AC_.jpg',
  'price': None,
  'description': 'Wireless Earbuds Sport,Bluetooth 5.1 Earphones Earhook,HD Stereo, Touch Control, USB-C & Wireless Charging,45H Playtime, Bluetooth Earbuds Sport IPX7,in Ear Headphones Mic for Sports Running Workout45 Hours of Playtime:Sport earbuds bluetooth can provide up to 7.5 hours of playtime, and the charging case can provide additional 5 charges, so that the total playtime reaches 45 hours which provides impressive music enjoy all-day.USB-C Quick & Wireless Charging: You can use the USB type-c cable to get quick wired charging, only 10 minutes of charging gets you 1.5 hours of use. The portable case also supports wireless charging for easy charge, so you can also simply lay the case on a wireless charger (sold separately) for convenient wireless charging.Smart Touch Control: Zeussa R1 offers advanced touch control allowing phone-free control of play, pause, mute, volume and track settings and can even active Siri and Google assistants, with the controls easily activated and changed by a simple touch to the earbuds.Bluetooth 5.1: Sport Earbuds blurtooth use the most advanced Bluetooth 5.1 technology, which can achieve uninterrupted fast transmission and low latency. No matter if it is games, calls or sports, there is no need to worry about signal interruption.IPX7 Waterproof: Sport earphones bluetooth wireless has an advanced nano coating waterproof function, which can prevent rain or sweat from splashing, and is suitable for wearing in any sports.',
  'rerank_score': 0.67026305},
 {'product_id': 'B0B2R7WJMD',
  'rating': 4.5,
  'fusion_score': 0.25,
  'image': 'https://m.media-amazon.com/images/I/4162cfpcAXL._AC_.jpg',
  'price': 16.99,
  'description': 'ELECDER i45 On-Ear Headphones with Microphone - Foldable Stereo Bass Headphones with No-Tangle 1.5M Cord, 3.5MM Jack, Portable Wired Headphones for School/Kids/Teens/Smartphones/Travel/Tablet - Red【Immersive Hi-Fi Stereo Bass】 Built-in a 40mm audio driver to ensure rich bass and crisp midrange which provides the best sound reproduction for all your needs, while ideal sound isolation effect to eliminate annoying background noise.【Lightweight and Folding】 Padded ultra-soft ear cushions and headband provide a perfect custom fit for all users and a comfortable and Long-lasting listening experience while protecting the ears. Adjustable size slider and foldable design make it Space-Saving and easy to carry.【Durable and Tangle-free】 The rugged resilient plastic shell and no tangle 4.9 ft (1.5m) nylon woven rope ensure durability. Wired headphones are suitable for kids, children, adults, and are designed for school, online learning, training, home, office, Airport, Plane, Travel, and more.【Friendly Microphone Button】 Easy to answer or end calls, Play/Pause audio, and skip tracks forward and backward via in-line control. Wired headphones offer universal compatibility with all 3.5mm jack devices, such as smartphones, laptops, desktops, Kindle, computers, PCs, MP3, MP4, etc.【What You Get】 Elecder i45 headphones wired, user guide, our worry-free 24-month warranty, easy to contact and friendly customer service.',
  'rerank_score': 0.6650626},
 {'product_id': 'B09TDBTSNF',
  'rating': 4.3,
  'fusion_score': 0.2,
  'image': 'https://m.media-amazon.com/images/I/311dv5JI7DL._AC_.jpg',
  'price': 19.99,
  'description': 'iFory USB C Headphones, Hi-Res Type C Earphones in-Ear Earbud with Baried Suit with Microphone and Volume Control Compatible with Google Pixel LG Samsung Oneplus Sony MacBook Black…【Wide Compatibility】-The USB C earphones compatible with Samsung Galaxy S21, Ultra, S21 Plus, S21, Note 20 Ultra, OnePlus 9, Google Pixel 5, Sony Xperia, VIVO Y20s, iPad mini 6 2021,iPad Pro,Macbook Pro,Macbook Air,iPad Air 4th&5th gen, and other Type C device without 3.5mm port.【Built-in Mic & Volume Control】- The USB C headphones feature the Microphone and three-button controllers. It allows you to play/pause songs, skips the next/previous song without picking up your phone, easily access volume control during usage; The high-quality microphone which can hand-free calling, allow you to easily answer/end calls.【Hi-Res Sound Quality】- iFory Type C Hi-Res wired earbuds adopt the latest DAC chip to provide high-quality sound and a solid connection by converting standard resolution music to superior clear audio.These improvements greatly extend the life of wired headphones and give you a wider sound range and better bass than traditional 10mm speakers.【Ergonomic Headphone Design】the ergonomically built and ultra-lightweight in-ear earphone fit the ear perfectly without any pain even wearing them all day long. With a durable design with high-quality materials, each wire have inside oxygen-free copper wire technology and sweat proof making it perfect for daily use. And it could also reduce the sound of the surrounding environment about 30db.【Super Durable Quality Material】high quality in materials inside each wire have inside oxygen-free copper wire technology, Nylon cable suit stretch resistant, long-lasting; 1.1 meters length, nylon braided cord, got through 8000+ bend bears test, which is durable for daily usage. Easy for carrying, you can enjoy music with it wherever and whenever.',
  'rerank_score': 0.6615731},
 {'product_id': 'B09PG1T4L8',
  'rating': 3.3,
  'fusion_score': 0.5,
  'image': 'https://m.media-amazon.com/images/I/31Zl9fjbQDL._AC_.jpg',
  'price': None,
  'description': 'Wireless EarbudsWireless Earbuds.Wireless Earbuds.Wireless Earbuds.Wireless Earbuds.Wireless Earbuds.',
  'rerank_score': 0.6545415},
 {'product_id': 'B0BRXXVDSW',
  'rating': 4.5,
  'fusion_score': 0.2,
  'image': 'https://m.media-amazon.com/images/I/417MBk0dpDL._AC_.jpg',
  'price': None,
  'description': 'PocBuds Wireless Earbuds Sports Headphones Headset with Charging Case90Hrs Playtime with 2200mAh Charging Case: Bluetooth headphones are equipped with a 75mAh battery to get 10 hours of music from a single charge of the workout earbuds. Add an extra 8 full recharges up to 90 hours of listening time combined with the included charging case. More than 2 hours playtime with a 15-minute quick charge on the go, so you can keep your music going with no interruptions at all. (10-12hrs in buds with 60%-80% volume)Dual LED Digital Display: Wireless earbuds with digital screen show the remaining power of the charging case by the left number and the charging status of the ear buds by the right LED light bar, which can intuitively reflect real time power to ensure timely charging and embody the sense of technology. The case presents its battery levels from 1 to 100. Once earphones are placed back into the charging case, which will begin to charge, and stop flashing until fully charged.Immersive Audio Experience & Crystal Clear Calls: Wireless headphones features an 11mm speaker with dual-chamber acoustic drivers for bass and crisp stereo sound that will immerse you in your music and give you a private concert listening experience. The built-in dual beam forming microphone target your voice and filter partial noise, which allowing you to catch every word of the call and have a great conversation without take the bluetooth earphones off.One-step Pairing & Dual Audio Control: Bluetooth earphones are easy and fast to pair with your device by opening the charging case and taking earbuds out. Ear phones compatible with mobile phones and any devices with Bluetooth-enabled. Multi-functional physical and volume control button are sturdy and responsive, no worry of accidental touching. Bluetooth connectivity can be maintained within 30 feet which can free your hands to easily control audio play and calls without operating your phone.Designed for Sports & IPX7 Sweatproof: Bluetooth earbuds are ergonomically designed with flexible earhooks and three different sizes of silicone eartips so that wireless earphones can fit your ears comfortably. No need to worry about shifting or falling out, they will stay in place even when doing exercise. IPX7 sweatproof can effectively resist sweat and rain without worrying about damaging the headphones, perfect for your workout, gym or running. The charging case is not waterproof.Support Wireless & Type-C Charging: The charging case for headphones wireless bluetooth supports wireless and Type-C charging, which make charging more convenient. Wireless charging gets rid of the cable and simply keeps the LED display facing up on top of any Qi-certified charging mat (not included). Type-C charging just use the included USB-C cable and a charging adapter (not included) to charge. Fully charge the charging case takes 3 hours via Type-C cable or about 6 hours via charging mat.',
  'rerank_score': 0.6527729},
 {'product_id': 'B08Y8QFQGM',
  'rating': 4.3,
  'fusion_score': 0.16666667,
  'image': 'https://m.media-amazon.com/images/I/41xd6QKUQpL._AC_.jpg',
  'price': None,
  'description': 'occiam Wireless Earbuds Bluetoth Headphones 48H Play Back Earphones in Ear TWS Waterproof with Microphone LED Display for Sports Running Workout GreenLED Power Display for Charging Case. Occiam sports bluetoth headphones charging case with led power Display shows remaining power in percentage.Charging case presents its battery from 1% to 100%. For the right or the left true wireless earbuds, while the earbud is chariging, the led bars of the earbud will flash, once the earbud are fully charged, the led bars of the earbud have no light flashing.48Hrs Battery Life with Charging Case. Built in 600mAh charging case. The both earbuds can last for 8Hours music time on a single 1.5hours charge. The charging case can charge the twin sports earbuds for 6 times, with the portable charging case you will get 48hrs playing music.Engineered design for sports. Adjustable and secure fit silicone ear hooks and ergonomic design ensure the sports earbuds stay comfortably firm in place when doing sports, running,other outside activity etc.Equipped with 3 pairs of different sizes of spare ear caps for options. Even do strenuous exercise, the earbuds will not fall off. And IPX5 splashproof protects the sports wireless earphones from water drop or sweat damageOne Step Auto Pairing. Picking up occiam sports Earphones from charging case,they will power on and pair with each other automatically.Then active mobile phone bluetoth to search “T17” to connect. After the first successful connection,the sports earbuds will automatically connect to the last paired device when reboot.When using single earphone, just take out the second one to achieve seamless transformation between single mode and twin mode.Sound Quality. The microphones of earbuds reduce background noise,make phone calls from stable signal and low power consumption.Each sport earbud has buttons to control the function of answer and reject phone, volume adjustment,switch music ,voice assisatant. Stereo sound,handsfree calling during sports anytime and anywhere.',
  'rerank_score': 0.6456563},
 {'product_id': 'B0B2757LDP',
  'rating': 4.3,
  'fusion_score': 0.5,
  'image': 'https://m.media-amazon.com/images/I/41UU3+gosgL._AC_.jpg',
  'price': 8.99,
  'description': 'Cleaner Kit for AirPod Pro 1 2 3, AMEAMI Earbud Cleaning Pen Tool for iPhone Samsung Lego Huawei MI Wireless Headphone (White)🔴【SEPARATED DUAL HEAD DESIGN】3-in-1 airpods cleaning kit with Flocking Sponge, High-density Brush and Metal Pen Tip, meet a variety of cleaning airpods, earbuds, headphone, earphone, case needs🔴【HIGH-DENSITY BRUSH & FLOCKING SPONGE】There are a soft microfiber brush and a lightweight flocking sponge above the cleaning pen, which can deeply clean the small parts, holes and charging bin of the AirPods. It is beneficial to improve headphones sound quality, charging efficiency and prolong service life.🔴【METAL CLEANER PEN TIP】Metal cleaning pen tip can clean the stubborn dust, thoroughly clean the gap.🔴【PERFECT COMBINATION】You will get a 3-in-1 airpod cleaning kit and 6 pieces of wet & dry wipe. It will keep your airpods or wireless headphones as clean as possible. This combination is the result of our survey of 1000+ airpods users.🔴【WIDE RANGE APPLICATION】This cleaning pen can not only clean the earphones, but also the earphone charging box, mobile phone earpieces, microphones, etc. compatible with most Bluetooth earphones on the market.',
  'rerank_score': 0.56563467}]